### PR TITLE
Some boundary checking to keep working

### PR DESCRIPTION
**Pull request by heynemann**
I was getting tons of `'NoneType' object has no attribute 'infer'` errors when using pylint-mongoengine.

By doing some boundary checks I managed to get it working fine.

Hope it helps.

### CODE REVIEW

**Comment by jucacrispim** [comment]
Hello, @heynemann 

It did help. Thank you very much!

Before merging the pr I was trying to understand why was that and I could not get any errors like yours - using old versions of astroid I got tons of other stuff. Could you provide some piece of code that was triggering the errors and show the packages' versions you're using (a pip freeze may help)?

Also, could you provide tests for your changes?

**Comment by heynemann** [comment]
The errors can be seen at [this file](https://github.com/heynemann/fastlane/blob/master/fastlane/api/task.py). Not sure why.

I can definitely provide tests, if I do understand why it was failing, as I don't. I did not spend much time debugging. I found out that there were issues with boundary checks and included those.

Maybe if you can help me understand why it happens I can try to provide meaningful tests.

**Comment by heynemann** [comment]
Btw, fastlane uses poetry, so all dependencies are locked.

**Comment by jucacrispim** [comment]
That was really helpfull. Thanks!

I've opened pr #4 where the issue is better explained. Using your changes and some added tests that pr was merged. So I'm closing this one.

A new version (0.2.2) is available at PyPI.

In fact, I've used some of your changes, the ones that seems to be related with the issues. Running it against fastlane was ok. If you have some code with other issues that are related with your other changes feel free to send the errors.

Thank you very much for your help!

**Pull request closed without merging**
